wheel_model:
  description: 'Wheel model'
  choices: ['nadia', 'moog']
  default_value: 'moog'
laser_model:
  description: 'Base laser model'
  choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
  default_value: 'sick-571'
add_on_module:
  description: 'Whether the base has an extra add on module'
  choices: ['no-add-on', 'rgbd-sensors']
  default_value: 'no-add-on'
