wheel_model:
  description: 'Wheel model'
  choices: ['nadia', 'moog']
  default_value: 'moog'
laser_model:
  description: 'Base laser model'
  choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
  default_value: 'sick-571'
has_courier_rgbd_sensors:
  description: 'Whether the base has RGBD sensors or not'
  choices: ['True', 'False']
  default_value: 'False'
